package ch.hslu.edu.enapp.webshop.ItemService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-15T02:14:16.508+01:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "urn:microsoft-dynamics-schemas/page/item", name = "Item_Port")
@XmlSeeAlso({ObjectFactory.class})
public interface ItemPort {

    @WebMethod(operationName = "Update", action = "urn:microsoft-dynamics-schemas/page/item:Update")
    @RequestWrapper(localName = "Update", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.Update")
    @ResponseWrapper(localName = "Update_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.UpdateResult")
    public void update(

        @WebParam(mode = WebParam.Mode.INOUT, name = "Item", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        javax.xml.ws.Holder<Item> item
    );

    @WebMethod(operationName = "IsUpdated", action = "urn:microsoft-dynamics-schemas/page/item:IsUpdated")
    @RequestWrapper(localName = "IsUpdated", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.IsUpdated")
    @ResponseWrapper(localName = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.IsUpdatedResult")
    @WebResult(name = "IsUpdated_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    public boolean isUpdated(

        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        java.lang.String key
    );

    @WebMethod(operationName = "Create", action = "urn:microsoft-dynamics-schemas/page/item:Create")
    @RequestWrapper(localName = "Create", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.Create")
    @ResponseWrapper(localName = "Create_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.CreateResult")
    public void create(

        @WebParam(mode = WebParam.Mode.INOUT, name = "Item", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        javax.xml.ws.Holder<Item> item
    );

    @WebMethod(operationName = "ReadMultiple", action = "urn:microsoft-dynamics-schemas/page/item:ReadMultiple")
    @RequestWrapper(localName = "ReadMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.ReadMultiple")
    @ResponseWrapper(localName = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.ReadMultipleResult")
    @WebResult(name = "ReadMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    public ch.hslu.edu.enapp.webshop.ItemService.ItemList readMultiple(

        @WebParam(name = "filter", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        java.util.List<ch.hslu.edu.enapp.webshop.ItemService.ItemFilter> filter,
        @WebParam(name = "bookmarkKey", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        java.lang.String bookmarkKey,
        @WebParam(name = "setSize", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        int setSize
    );

    @WebMethod(operationName = "UpdateMultiple", action = "urn:microsoft-dynamics-schemas/page/item:UpdateMultiple")
    @RequestWrapper(localName = "UpdateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.UpdateMultiple")
    @ResponseWrapper(localName = "UpdateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.UpdateMultipleResult")
    public void updateMultiple(

        @WebParam(mode = WebParam.Mode.INOUT, name = "Item_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        javax.xml.ws.Holder<ItemList> itemList
    );

    @WebMethod(operationName = "Read", action = "urn:microsoft-dynamics-schemas/page/item:Read")
    @RequestWrapper(localName = "Read", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.Read")
    @ResponseWrapper(localName = "Read_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.ReadResult")
    @WebResult(name = "Item", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    public ch.hslu.edu.enapp.webshop.ItemService.Item read(

        @WebParam(name = "No", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        java.lang.String no
    );

    @WebMethod(operationName = "CreateMultiple", action = "urn:microsoft-dynamics-schemas/page/item:CreateMultiple")
    @RequestWrapper(localName = "CreateMultiple", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.CreateMultiple")
    @ResponseWrapper(localName = "CreateMultiple_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.CreateMultipleResult")
    public void createMultiple(

        @WebParam(mode = WebParam.Mode.INOUT, name = "Item_List", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        javax.xml.ws.Holder<ItemList> itemList
    );

    @WebMethod(operationName = "Delete", action = "urn:microsoft-dynamics-schemas/page/item:Delete")
    @RequestWrapper(localName = "Delete", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.Delete")
    @ResponseWrapper(localName = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item", className = "ch.hslu.edu.enapp.webshop.ItemService.DeleteResult")
    @WebResult(name = "Delete_Result", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
    public boolean delete(

        @WebParam(name = "Key", targetNamespace = "urn:microsoft-dynamics-schemas/page/item")
        java.lang.String key
    );
}
